---
# tasks file for apache
 - name: install httpd
   package:
        name: "{{package_name}}"
        state: present
      
 - name: start httpd deamon
   systemd:
        name: "{{ package_name }}"
        state: started
        enabled: true 
       
 - name: Copy HTML file
   copy:
        src: index.html
        dest: /var/www/html/index.html
        tags:
         - file_copy
   notify: restard apache